name: Generate Isometric Calendar

on:
  schedule:
    - cron: "0 0 * * *" # Chạy vào 0h mỗi ngày
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Isometric View
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Options: day, week, month, half-year, year
          filename: github-isometric-calendar.svg

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
          commit_message: "Build the City [bot]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}