name: Generate Isometric Calendar

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Isometric View
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Options: day, week, month, half-year, year
          filename: dist/github-isometric-calendar.svg
          output_action: none
          
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Build the City [bot]"
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}