name: Waka Readme

on:
  schedule:
    # At 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow the action to commit changes to the repository
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Visual configuration
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: false
          SECTION_NAME: wakatime
          BLOCKS: █▓▒░
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          
          # Bot configuration
          COMMIT_MESSAGE: "Update WakaTime Stats [bot] [skip ci]"
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"