name: Waka Readme

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab
  schedule:
    # At 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}